name: generate galaga game

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: generate galaga svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: daqsi1488
          games: galaga
      
      - name: deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "update galaga game"
